### PR TITLE
Add boot scripts for the V4H Whitehawk

### PR DESCRIPTION
**Pull request by rshym**
These scripts were tested on the Whitehawk board.

### CODE REVIEW

**Comment by lorc** [comment]
Are you sure that this is a good idea? For me, as developer, it would be very frustrating if I am not able to alter XEN command line. Maybe we should add optional `xen_bootargs` variable? If it present, it's value will overwrite `bootargs`, if not present - `bootargs` will be removed. 

As a side note, in similar fashion we can implement `dom0_bootargs` variable that will change entries in DTS... but this is a topic for another PR.

**Comment by rshym** [comment]
My point is that we should make build, boot, other instructions as small as possible. The fewer steps users have to do - the better.

At the same time, convenience of the development team is less significant. In any case, when developer is doing developer's things, he/she may do any changes required, including modification of the boot scripts, or use it's own set of u-boot commands for booting. Any way, it's a developer, who knows what is needed.
And I consider boot scripts as very convenient way for the customers to boot the whole system "out of the box", with minimal interaction.

That's the reasoning behind this PR.
If it's not compelling enough, I'm OK with the dropping `env delete bootargs` from the PR.

**Comment by rshym** [comment]
Also, one more thing. Maybe it's a good idea to consider adding the `setenv bootcmd 'ext4load mmc 0:1 0x83000000 boot-emmc.uImage; source 0x83000000'` to the u-boot's default environment. So, we can start the board just after the flashing of the IPLs and the image. In that case, we just need to ask users to 
- flash IPLs
- restart the board
- run `env set default; saveenv`
- reboot the board

But this idea needs additional discussion.

**Comment by lorc** [comment]
> At the same time, convenience of the development team is less significant.

This change will affect prod-devel as well... 

> If it's not compelling enough, I'm OK with the dropping `env delete bootargs` from the PR.

I didn't tried this, but probably you can just replace that with `setenv bootargs $xen_bootargs` and that's all. If this variable is not defined, you will get the same behavior as with `env delete` but it will allow bootargs customization nevertheless.

>  So, we can start the board just after the flashing of the IPLs and the image. In that case, we just need to ask users to [...]

Sounds like a great idea, actually.

**Comment by rshym** [comment]
> This change will affect prod-devel as well...
No, it will not. This affects only meta-xt-gateway. So, only rcar4 is affected. Also, we do not use boot-scripts for the rcar3. Unfortunatelly.

> setenv bootargs $xen_bootargs
Thanks, that looks much better than the solution proposed in this PR. I will rework the PR.

**Comment by rshym** [comment]
After some considerations, I decided to drop the second commit, that adds `env delete...`. Even in the proposed form `setenv bootargs $xen_bootargs`.

There are few reasons for dropping:
- I fully agree that `env delete ...` makes possible tuning/debugging more complex without significant advantages
- The possible solution to use `setenv bootargs $xen_bootargs` adds an additional variable without justification, because...
- We can provide updated instruction for the product `setenv bootcmd 'env delete bootargs; ext4load mmc 0:1 0x83000000 boot-emmc.uImage; source 0x83000000'`. Anyway, the user needs to set  `bootcmd`. And in the need, we are able to easily modify `bootcmd`.

So, I have dropped `env delete...` commit and removed that command from the whitehawk-related scripts in the first commit.

**Review by lorc — APPROVED** [review]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`R-b` is added.
Scripts were tested on the Whitehawk board.
Ready to be merged.

**Pull request merged**
